---
version: "3"

services:
  database:
    container_name: machinery_db
    image: mongo:5
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=machinery

  api:
    container_name: machinery_api
    build: .
    depends_on:
      - database
    environment:
      - MONGO_URI=mongodb://user:password@database/machinery?authSource=admin
    healthcheck:
      test: ["CMD-SHELL", "curl -X POST http://localhost:5000/s || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - 5000:5000
