#!/bin/sh

##
#  This file is for CI purpose. will be surelly modified / removed later
##

export FLASK_ENV=development
export FLASK_DEBUG=1
export FLASK_APP=examples.services.upper.app:create_app

flask run --host=0.0.0.0 --port=5001
